# -*- coding: utf-8 -*-
"""matplotlib_i.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pf0wLUq70fWj3-QptIi2C3SIMCUIqcF8

# **Python**
## Librería **matplotlib**
### Documentación:
[Documentación oficial en matplotlib.org](https://matplotlib.org/stable/)
### Laboratorio:
"""

import matplotlib.pyplot as plt

# Data de ejemplo
meses = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']
ventas2024 = [15000,35000,32000,19000,20000,18000,15400,36000,37000,41254,35214,32333]
ventas2023 = [17500,28000,39000,40000,37685,26000,22400,21000,23000,18254,12014,14333]

# Crear gráfico de líneas
plt.plot(meses, ventas2024, marker='o', linestyle='-', linewidth=2, color='b', label='Ventas/Mes 2024')
plt.plot(meses, ventas2023, marker='o', linestyle='-', linewidth=2, color='r', label='Ventas/Mes 2023')

# Titulo de gráfico
plt.title('Ventas Mensuales 2024/23')

# Etiquetas de series de datos
plt.xlabel('Meses')
plt.ylabel('Ventas/mes ($)')

# Leyenda de series en gráfico
plt.legend()

# Cuadricula
plt.grid(True, linestyle='--', color='gray', alpha=0.5)

# Visualizar gráfico
plt.show()

"""## Parámetros de plt.plot



*   marker
   *   círculo 'o', triangulo '^', cuadrado 's', diamante 'D', cruz '+', 'X' 'x', punto '.'
*   linestyle
   *   continua '-', discontinua '--', raya punto '-.', puntos ':'
*   linewidth
   *   ancho de línea en puntos
*   color
   *   r red, b blue, g green, etc.
*   label
   *   etiqueta para la serie de datos



"""